{% set name = "xarray-dataclass" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xarray-contrib/xarray-dataclass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f1b602bbef535f68849b4bc02d4873986bf86110caeede85d0f90cf33af0195a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}.*
    - numpy >=2.0.0
    - xarray >=2022.3
    - typing_extensions >=4.10.0

test:
  imports:
    - xarray_dataclass
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - python >={{ python_min }}.*
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/xarray-contrib/xarray-dataclass
  summary: xarray data creation by data classes
  description: |
    array-dataclass is a Python package that makes it easy to create xarray's DataArray and Dataset objects that are 
    "typed" (i.e. fixed dimensions, data type, coordinates, attributes, and name) using the Python's dataclass.
  doc_url: https://xarray-contrib.github.io/xarray-dataclass/
  dev_url: https://github.com/xarray-contrib/xarray-dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonora
    - thewtex
    - ianhi
